-- MySQL Script generated by MySQL Workbench
-- Thu Jun 20 15:04:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bbllbrnvl1fqjnvn2k4s
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bbllbrnvl1fqjnvn2k4s` ;

-- -----------------------------------------------------
-- Schema bbllbrnvl1fqjnvn2k4s
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bbllbrnvl1fqjnvn2k4s` DEFAULT CHARACTER SET utf8 ;
USE `bbllbrnvl1fqjnvn2k4s` ;

-- -----------------------------------------------------
-- Table `bbllbrnvl1fqjnvn2k4s`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbllbrnvl1fqjnvn2k4s`.`materias` ;

CREATE TABLE IF NOT EXISTS `bbllbrnvl1fqjnvn2k4s`.`materias` (
  `id_materia` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_materia` VARCHAR(45) NULL DEFAULT NULL,
  `id_curso` INT(11) NULL DEFAULT NULL,
  `id_profesor` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbllbrnvl1fqjnvn2k4s`.`especialidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbllbrnvl1fqjnvn2k4s`.`especialidades` ;

CREATE TABLE IF NOT EXISTS `bbllbrnvl1fqjnvn2k4s`.`especialidades` (
  `id_especialidades` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_especialidad` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_especialidades`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbllbrnvl1fqjnvn2k4s`.`tipos_de_documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbllbrnvl1fqjnvn2k4s`.`tipos_de_documentos` ;

CREATE TABLE IF NOT EXISTS `bbllbrnvl1fqjnvn2k4s`.`tipos_de_documentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_de_documento` VARCHAR(50) NULL DEFAULT NULL,
  `abreviatura` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbllbrnvl1fqjnvn2k4s`.`profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbllbrnvl1fqjnvn2k4s`.`profesores` ;

CREATE TABLE IF NOT EXISTS `bbllbrnvl1fqjnvn2k4s`.`profesores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT NULL,
  `id_especialidad` INT(11) NULL DEFAULT NULL,
  `numero_documento` INT(11) NULL DEFAULT NULL,
  `id_materia` INT(11) NULL DEFAULT NULL,
  `id_tipo_de_documento` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profesores_1_idx` (`id_materia` ASC) VISIBLE,
  INDEX `fk_profesores_2_idx` (`id_especialidad` ASC) VISIBLE,
  INDEX `fk_profesores_3_idx` (`id_tipo_de_documento` ASC) VISIBLE,
  CONSTRAINT `fk_profesores_1`
    FOREIGN KEY (`id_materia`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`materias` (`id_materia`),
  CONSTRAINT `fk_profesores_2`
    FOREIGN KEY (`id_especialidad`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`especialidades` (`id_especialidades`),
  CONSTRAINT `fk_profesores_3`
    FOREIGN KEY (`id_tipo_de_documento`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`tipos_de_documentos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbllbrnvl1fqjnvn2k4s`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbllbrnvl1fqjnvn2k4s`.`cursos` ;

CREATE TABLE IF NOT EXISTS `bbllbrnvl1fqjnvn2k4s`.`cursos` (
  `id_curso` INT(11) NOT NULL AUTO_INCREMENT,
  `id_profesor_encargado` INT(11) NULL DEFAULT NULL,
  `nombre_del_curso` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_curso`),
  CONSTRAINT `fk_cursos_1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`profesores` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbllbrnvl1fqjnvn2k4s`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbllbrnvl1fqjnvn2k4s`.`roles` ;

CREATE TABLE IF NOT EXISTS `bbllbrnvl1fqjnvn2k4s`.`roles` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbllbrnvl1fqjnvn2k4s`.`escuelas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbllbrnvl1fqjnvn2k4s`.`escuelas` ;

CREATE TABLE IF NOT EXISTS `bbllbrnvl1fqjnvn2k4s`.`escuelas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `correo_electronico` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbllbrnvl1fqjnvn2k4s`.`directivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbllbrnvl1fqjnvn2k4s`.`directivos` ;

CREATE TABLE IF NOT EXISTS `bbllbrnvl1fqjnvn2k4s`.`directivos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT NULL,
  `fecha_inicio` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_rol` INT(11) NULL DEFAULT NULL,
  `id_escuela` INT(11) NULL DEFAULT NULL,
  `id_tipo_documento` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_directivos_1_idx` (`tipo_rol` ASC) VISIBLE,
  INDEX `fk_directivos_2_idx` (`id_escuela` ASC) VISIBLE,
  INDEX `fk_directivos_idx` (`id_tipo_documento` ASC) VISIBLE,
  CONSTRAINT `fk_directivos`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`tipos_de_documentos` (`id`),
  CONSTRAINT `fk_directivos_1`
    FOREIGN KEY (`tipo_rol`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`roles` (`id_rol`),
  CONSTRAINT `fk_directivos_2`
    FOREIGN KEY (`id_escuela`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`escuelas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbllbrnvl1fqjnvn2k4s`.`estudiantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbllbrnvl1fqjnvn2k4s`.`estudiantes` ;

CREATE TABLE IF NOT EXISTS `bbllbrnvl1fqjnvn2k4s`.`estudiantes` (
  `id_estudiantes` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `correo_electronico` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `numero_documento` VARCHAR(45) NULL DEFAULT NULL,
  `id_tipo_de_documento` INT(11) NULL DEFAULT NULL,
  `id_escuela` INT(11) NULL DEFAULT NULL,
  `id_curso` INT(11) NULL DEFAULT NULL,
  `id_profesor` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estudiantes`),
  INDEX `fk_estudiantes_1_idx` (`id_escuela` ASC) VISIBLE,
  INDEX `fk_estudiantes_2_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_estudiantes_3_idx` (`id_tipo_de_documento` ASC) VISIBLE,
  INDEX `fk_estudiantes_4_idx` (`id_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_estudiantes_1`
    FOREIGN KEY (`id_escuela`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`escuelas` (`id`),
  CONSTRAINT `fk_estudiantes_2`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`cursos` (`id_curso`),
  CONSTRAINT `fk_estudiantes_3`
    FOREIGN KEY (`id_tipo_de_documento`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`tipos_de_documentos` (`id`),
  CONSTRAINT `fk_estudiantes_4`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`profesores` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbllbrnvl1fqjnvn2k4s`.`inscripciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbllbrnvl1fqjnvn2k4s`.`inscripciones` ;

CREATE TABLE IF NOT EXISTS `bbllbrnvl1fqjnvn2k4s`.`inscripciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_curso` INT(11) NULL DEFAULT NULL,
  `id_estudiante` INT(11) NULL DEFAULT NULL,
  `fecha_inscripcion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_curso` (`id_curso` ASC) VISIBLE,
  INDEX `id_estudiante` (`id_estudiante` ASC) VISIBLE,
  CONSTRAINT `inscripciones_ibfk_1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`cursos` (`id_curso`),
  CONSTRAINT `inscripciones_ibfk_2`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `bbllbrnvl1fqjnvn2k4s`.`estudiantes` (`id_estudiantes`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
